### ISSUE TITLE
Netbeans用左你地隻字體, 唔錯

### ISSUE THREAD

**Issue by quantrpeter** [chiron-fonts/chiron-fonts.github.io#1]
![Screenshot_10](https://user-images.githubusercontent.com/50471577/110232476-d27a1d80-7f58-11eb-91ca-9e02e0d04fe7.png)
![Screenshot_11](https://user-images.githubusercontent.com/50471577/110232478-d443e100-7f58-11eb-97b9-a163c0852182.png)

**Comment by tamcy** [comment]
多謝，不過英文字主要係 思源黑體 嗰邊功勞，我冇做過改動 😅
